# 🎓 تحليل بيانات الجامعات المصرية
**الملف:** Universities_Egypt.csv  
**14 جامعة حكومية | 3 شعب | مجاميع القبول والنسب المئوية**

---

In [9]:
import pandas as pd
import numpy as np
# تحميل البيانات
df = pd.read_csv("D:\\pdf\\datesetuniversty\\Universities_Egypt.csv")
# معاينة أولية
print("شكل البيانات:", df.shape)
print("\nالأعمدة:")
print(df.columns.tolist())
df.head()

شكل البيانات: (2139, 13)

الأعمدة:
['University_uni', 'Faculty', 'Department', 'City', 'Type', 'Founded_Year_clean', 'University_clean', 'Stream', 'College Type', 'University_stream', 'Minimum Absolute Score', 'Minimum Percentage (%)', 'Stream_Type']

,University_uni,Faculty,Department,City,Type,Founded_Year_clean,University_clean,Stream,College Type,University_stream,Minimum Absolute Score,Minimum Percentage (%),Stream_Type
0,ain shams university,Faculty of Medicine,Internal Medicine,Cairo,Public,1950.0,ain shams university,Science-Math,Medicine (Medicine),Ain Shams University,397.0,96.8,Science
1,ain shams university,Faculty of Medicine,Internal Medicine,Cairo,Public,1950.0,ain shams university,Science-Science,Medicine (Medicine),Ain Shams University,395.0,96.3,Science
2,ain shams university,Faculty of Medicine,Internal Medicine,Cairo,Public,1950.0,ain shams university,Literary,Law (),Ain Shams University,270.0,71.1,Literary
3,ain shams university,Faculty of Medicine,Surgery,Cairo,Public,1950.0,ain shams university,Science-Math,Medicine (Medicine),Ain Shams University,397.0,96.8,Science
4,ain shams university,Faculty of Medicine,Surgery,Cairo,Public,1950.0,ain shams university,Science-Science,Medicine (Medicine),Ain Shams University,395.0,96.3,Science

## 1️⃣ نظرة عامة على البيانات

In [10]:
# معلومات عامة
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2139 entries, 0 to 2138
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   University_uni          2139 non-null   str
 1   Faculty                 2139 non-null   str
 2   Department              2139 non-null   str
 3   City                    2139 non-null   str
 4   Type                    2139 non-null   str
 5   Founded_Year_clean      2070 non-null   float64
 6   University_clean        2139 non-null   str
 7   Stream                  2139 non-null   str
 8   College Type            2139 non-null   str
 9   University_stream       2139 non-null   str
 10  Minimum Absolute Score  2139 non-null   float64
 11  Minimum Percentage (%)  2139 non-null   float64
 12  Stream_Type             2139 non-null   str
dtypes: float64(3), str(10)
memory usage: 217.4 KB

In [16]:
# إحصائيات وصفية للأعمدة الرقمية
df[['Minimum Absolute Score', 'Minimum Percentage (%)']].describe().round(1)

       Minimum Absolute Score  Minimum Percentage (%)
count                  2139.0                  2139.0
mean                    317.5                    79.3
std                      61.3                    13.1
min                     220.0                    57.9
25%                     260.0                    68.3
50%                     308.0                    75.1
75%                     388.0                    94.6
max                     398.5                    97.2

In [17]:
# القيم الفريدة في كل عمود نصي
for col in ['University_clean', 'Faculty', 'City', 'Stream', 'Stream_Type']:
    print(f"{col}: {df[col].nunique()} قيمة فريدة")

University_clean: 14 قيمة فريدة
Faculty: 16 قيمة فريدة
City: 13 قيمة فريدة
Stream: 3 قيمة فريدة
Stream_Type: 2 قيمة فريدة

## 2️⃣ استعلامات أساسية

In [18]:
# ── جميع الجامعات والمدن ──
df[['University_clean', 'City', 'Founded_Year_clean']].drop_duplicates().reset_index(drop=True)

           University_clean        City  Founded_Year_clean
0      ain shams university       Cairo              1950.0
1     alexandria university  Alexandria              1938.0
2         assiut university       Asyut              1957.0
3      beni-suef university   Beni-Suef              2005.0
4          cairo university        Giza              1908.0
5       damietta university    Damietta              2012.0
6         fayoum university      Faiyum              2005.0
7         helwan university       Cairo              1975.0
8       mansoura university    Mansoura              1972.0
9          minia university       Minya              1976.0
10  south valley university        Qena              1995.0
11    suez canal university    Ismailia                 NaN
12         tanta university       Tanta              1972.0
13       zagazig university     Zagazig              1974.0

In [19]:
# ── عدد الكليات لكل جامعة ──
df.groupby('University_clean')['Faculty'].nunique().sort_values(ascending=False).reset_index()  .rename(columns={'Faculty': 'عدد الكليات'})

           University_clean  عدد الكليات
0      ain shams university           16
1     alexandria university           16
2         assiut university           16
3      beni-suef university           16
4          cairo university           16
5       damietta university           16
6         fayoum university           16
7         helwan university           16
8       mansoura university           16
9          minia university           16
10  south valley university           16
11    suez canal university           16
12         tanta university           16
13       zagazig university           16

In [20]:
# ── عدد الأقسام لكل كلية (على مستوى كل الجامعات) ──
df.groupby('Faculty')['Department'].nunique().sort_values(ascending=False).reset_index()  .rename(columns={'Department': 'عدد الأقسام'})

                                 Faculty  عدد الأقسام
0                     Faculty of Science            6
1                    Faculty of Medicine            6
2                 Faculty of Agriculture            5
3                        Faculty of Arts            5
4                 Faculty of Engineering            5
5         Faculty of Veterinary Medicine            5
6                         Faculty of Law            4
7                    Faculty of Commerce            4
8               Faculty of Physiotherapy            4
9    Faculty of Oral and Dental Medicine            4
10                Faculty of Dar El-Ulum            4
11         Faculty of Mass Communication            4
12                   Faculty of Pharmacy            4
13  Faculty of Computers and Information            3
14               Faculty of Kindergarten            3
15                    Faculty of Nursing            3

## 3️⃣ تحليل مجاميع القبول

In [21]:
# ── أعلى وأقل مجموع لكل شعبة ──
df.groupby('Stream')['Minimum Absolute Score'].agg(['min','max','mean']).round(2)  .rename(columns={'min':'أقل مجموع','max':'أعلى مجموع','mean':'متوسط'})  .reset_index()

            Stream  أقل مجموع  أعلى مجموع   متوسط
0         Literary      220.0       272.0  252.50
1     Science-Math      306.0       398.5  363.95
2  Science-Science      280.0       396.5  350.94

In [22]:
# ── ترتيب الجامعات حسب المجموع — شعبة علمي رياضة ──
(
    df[df['Stream'] == 'Science-Math']
    .drop_duplicates('University_clean')
    [['University_clean','City','Minimum Absolute Score','Minimum Percentage (%)']]
    .sort_values('Minimum Absolute Score', ascending=False)
    .reset_index(drop=True)
)

,University_clean,City,Minimum Absolute Score,Minimum Percentage (%)
0,cairo university,Giza,398.5,97.2
1,ain shams university,Cairo,397.0,96.8
2,alexandria university,Alexandria,396.0,96.6
3,mansoura university,Mansoura,392.0,95.6
4,assiut university,Asyut,390.0,95.1
5,zagazig university,Zagazig,382.0,93.2
6,helwan university,Cairo,380.0,92.7
7,tanta university,Tanta,328.0,80.0
8,suez canal university,Ismailia,326.0,79.5
9,fayoum university,Faiyum,308.0,75.1
10,south valley university,Qena,306.0,74.6

In [23]:
# ── ترتيب الجامعات حسب المجموع — شعبة علمي علوم ──
(
    df[df['Stream'] == 'Science-Science']
    .drop_duplicates('University_clean')
    [['University_clean','City','Minimum Absolute Score','Minimum Percentage (%)']]
    .sort_values('Minimum Absolute Score', ascending=False)
    .reset_index(drop=True)
)

,University_clean,City,Minimum Absolute Score,Minimum Percentage (%)
0,cairo university,Giza,396.5,96.7
1,ain shams university,Cairo,395.0,96.3
2,alexandria university,Alexandria,388.0,94.6
3,mansoura university,Mansoura,378.0,92.2
4,minia university,Minya,312.0,76.1
5,beni-suef university,Beni-Suef,298.0,72.7
6,helwan university,Cairo,280.0,68.3

In [24]:
# ── ترتيب الجامعات حسب المجموع — شعبة أدبي ──
(
    df[df['Stream'] == 'Literary']
    .drop_duplicates('University_clean')
    [['University_clean','City','Minimum Absolute Score','Minimum Percentage (%)']]
    .sort_values('Minimum Absolute Score', ascending=False)
    .reset_index(drop=True)
)

,University_clean,City,Minimum Absolute Score,Minimum Percentage (%)
0,cairo university,Giza,272.0,71.6
1,ain shams university,Cairo,270.0,71.1
2,alexandria university,Alexandria,268.0,70.5
3,mansoura university,Mansoura,258.0,67.9
4,helwan university,Cairo,256.0,67.4
5,zagazig university,Zagazig,254.0,66.8
6,tanta university,Tanta,240.0,63.2
7,damietta university,Damietta,238.0,62.6
8,beni-suef university,Beni-Suef,220.0,57.9

## 4️⃣ استعلامات التصفية والفلترة

In [25]:
# ── الكليات المتاحة في جامعة معينة (غيّر الاسم حسب ما تريد) ──
UNIVERSITY = 'cairo university'  # ← غيّر هنا

df[df['University_clean'] == UNIVERSITY]['Faculty'].unique()

<StringArray>
[                 'Faculty of Medicine',
               'Faculty of Engineering',
                   'Faculty of Science',
               'Faculty of Agriculture',
                  'Faculty of Commerce',
                       'Faculty of Law',
                      'Faculty of Arts',
                  'Faculty of Pharmacy',
 'Faculty of Computers and Information',
        'Faculty of Mass Communication',
                   'Faculty of Nursing',
             'Faculty of Physiotherapy',
  'Faculty of Oral and Dental Medicine',
       'Faculty of Veterinary Medicine',
               'Faculty of Dar El-Ulum',
              'Faculty of Kindergarten']
Length: 16, dtype: str

In [26]:
# ── الجامعات التي تقبل بمجموع أقل من قيمة معينة (علمي رياضة) ──
MIN_SCORE = 350  # ← غيّر حسب مجموعك

(
    df[(df['Stream'] == 'Science-Math') & (df['Minimum Absolute Score'] <= MIN_SCORE)]
    .drop_duplicates('University_clean')
    [['University_clean','City','Minimum Absolute Score','Minimum Percentage (%)']]
    .sort_values('Minimum Absolute Score')
    .reset_index(drop=True)
)

,University_clean,City,Minimum Absolute Score,Minimum Percentage (%)
0,south valley university,Qena,306.0,74.6
1,fayoum university,Faiyum,308.0,75.1
2,suez canal university,Ismailia,326.0,79.5
3,tanta university,Tanta,328.0,80.0

In [27]:
# ── ابحث عن كلية معينة في كل الجامعات ──
FACULTY = 'Faculty of Medicine'  # ← غيّر هنا

(
    df[df['Faculty'] == FACULTY]
    .drop_duplicates('University_clean')
    [['University_clean','City','Stream','Minimum Absolute Score']]
    .sort_values('Minimum Absolute Score', ascending=False)
    .reset_index(drop=True)
)

,University_clean,City,Stream,Minimum Absolute Score
0,cairo university,Giza,Science-Math,398.5
1,ain shams university,Cairo,Science-Math,397.0
2,alexandria university,Alexandria,Science-Math,396.0
3,mansoura university,Mansoura,Science-Math,392.0
4,assiut university,Asyut,Science-Math,390.0
5,zagazig university,Zagazig,Science-Math,382.0
6,helwan university,Cairo,Science-Math,380.0
7,tanta university,Tanta,Science-Math,328.0
8,suez canal university,Ismailia,Science-Math,326.0
9,minia university,Minya,Science-Science,312.0
10,fayoum university,Faiyum,Science-Math,308.0
11,south valley university,Qena,Science-Math,306.0
12,beni-suef university,Beni-Suef,Science-Science,298.0
13,damietta university,Damietta,Literary,238.0

In [28]:
# ── جامعات مدينة معينة ──
CITY = 'Cairo'  # ← غيّر هنا

df[df['City'] == CITY][['University_clean','Faculty','Department']].drop_duplicates().reset_index(drop=True)

         University_clean                  Faculty                 Department
0    ain shams university      Faculty of Medicine          Internal Medicine
1    ain shams university      Faculty of Medicine                    Surgery
2    ain shams university      Faculty of Medicine                 Pediatrics
3    ain shams university      Faculty of Medicine    Obstetrics & Gynecology
4    ain shams university      Faculty of Medicine               Pharmacology
..                    ...                      ...                        ...
133     helwan university   Faculty of Dar El-Ulum             Quran Sciences
134     helwan university   Faculty of Dar El-Ulum                   Theology
135     helwan university  Faculty of Kindergarten  Early Childhood Education
136     helwan university  Faculty of Kindergarten           Child Psychology
137     helwan university  Faculty of Kindergarten     Curriculum Development

[138 rows x 3 columns]

## 5️⃣ مقارنات متقدمة

In [ ]:
# ── مقارنة جامعتين في الشعب الثلاثة ──
UNI_A = 'cairo university'
UNI_B = 'ain shams university'

comparison = df[df['University_clean'].isin([UNI_A, UNI_B])]\    .groupby(['University_clean','Stream'])['Minimum Absolute Score']\    .first().unstack('Stream').round(2)

comparison

In [ ]:
# ── pivot table: متوسط المجموع لكل جامعة × كل شعبة ──
pivot = df.pivot_table(
    index='University_clean',
    columns='Stream',
    values='Minimum Absolute Score',
    aggfunc='mean'
).round(2)

pivot

In [29]:
# ── الجامعة الأقدم والأحدث ──
age_df = df[['University_clean','Founded_Year_clean']].drop_duplicates().dropna()
print("الأقدم:", age_df.loc[age_df['Founded_Year_clean'].idxmin()].values)
print("الأحدث:", age_df.loc[age_df['Founded_Year_clean'].idxmax()].values)

الأقدم: ['cairo university' np.float64(1908.0)]
الأحدث: ['damietta university' np.float64(2012.0)]

In [ ]:
# ── عدد الأقسام لكل جامعة (الأكثر تنوعاً) ──
df.groupby('University_clean')['Department'].nunique()\  .sort_values(ascending=False)\  .reset_index()\  .rename(columns={'Department': 'عدد الأقسام'})

## 6️⃣ استعلام مخصص — أدخل مجموعك واعرف أقبل فين
غيّر القيم في الخلية دي حسب وضعك:

In [31]:

#  ← غيّر القيم دي حسب حالتك       
MY_SCORE  = 380          # مجموعك
MY_STREAM = 'Science-Math'  # Science-Math | Science-Science | Literary


result = (
    df[
        (df['Stream'] == MY_STREAM) &
        (df['Minimum Absolute Score'] <= MY_SCORE)
    ]
    .drop_duplicates('University_clean')
    [['University_clean','City','Minimum Absolute Score','Minimum Percentage (%)']]
    .sort_values('Minimum Absolute Score', ascending=False)
    .reset_index(drop=True)
)

print(f"بمجموع {MY_SCORE} في شعبة {MY_STREAM}، تقدر تقبل في {len(result)} جامعة:")
result

بمجموع 380 في شعبة Science-Math، تقدر تقبل في 5 جامعة:

,University_clean,City,Minimum Absolute Score,Minimum Percentage (%)
0,helwan university,Cairo,380.0,92.7
1,tanta university,Tanta,328.0,80.0
2,suez canal university,Ismailia,326.0,79.5
3,fayoum university,Faiyum,308.0,75.1
4,south valley university,Qena,306.0,74.6